modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "correct_gaming_posture"
version = "${version}_neoforge"
displayName = "Correct Gaming Posture"
authors = ["Blexyel", "ganzuul"]
description = '''
Head-tracking camera support with posture-focused controls, zoom, and freelook.
'''
logoFile = "assets/correct_gaming_posture/icon.png"

[[dependencies.correct_gaming_posture]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.correct_gaming_posture]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.correct_gaming_posture]]
modId = "architectury"
type = "required"
versionRange = "[13.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.correct_gaming_posture]]
modId="yet_another_config_lib_v3"
mandatory=true
versionRange="*"
ordering="NONE"
side="CLIENT"

[[mixins]]
config = "correct-gaming-posture.mixins.json"
