modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "simple_camera_tweaks"
version = "${version}_neoforge"
displayName = "simple-camera-tweaks"
authors = "Blexyel"
description = '''
simple camera tweaks ig.
Adds freelook, zoom and double hands.
'''
logoFile = "assets/simple_camera_tweaks/icon.png"

[[dependencies.simple_camera_tweaks]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simple_camera_tweaks]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simple_camera_tweaks]]
modId = "architectury"
type = "required"
versionRange = "[13.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.simple_camera_tweaks]]
modId="yet_another_config_lib_v3"
mandatory=true
versionRange="*"
ordering="NONE"
side="CLIENT"

[[mixins]]
config = "simple-camera-tweaks.mixins.json"
